//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

declare module GameSDK {
	export class GameTelemetry
	{
		public gameTime: string;
		public timeToSleep: string;
		public currentSpeed: GameSDK.Speed;
		public speedLimit: GameSDK.Speed;
		public coordinates: GameSDK.Coordinates;
		public fuelAmount: number;
		public totalFuelCapacity: number;
		public estimatedFuelRange: number;
		public jobDistance: number;
		public currentJobTravelledDistance: number;
		public originCity: string;
		public destinationCity: string;
	}
	export class Speed
	{
		public kph: number;
		public mph: number;
	}
	export class Coordinates
	{
		public latitude: string;
		public longitude: string;
	}
}
